{
    'name': 'Veterinary Clinic',
    'summary': """ EquiClinic """,
    'description': """ EquiClinic """,
    'version': '1.11.2',
    'category': 'Clinic',
    'website': '',
    "author": " Bilal ",
    'license': 'LGPL-3',
    'depends': ['account', 'base', 'mail', 'attachment_indexation'],
    'data': [
        'data/evaluation_stage.xml',
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/seq.xml',
        'views/menu.xml',
        'views/animal.xml',
        'wizard/canelreason.xml',
        'wizard/mail_compose_message_view.xml',
        'views/appointment.xml',
        'views/evaluation.xml',
        'views/evaluation_stages.xml',
        'reports/report.xml',
        'views/email_templates.xml',
    ],
    'demo': [
        'demo/demo.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
